### ISSUE TITLE
Layout - Application Layers doc edit

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/design-system#295]
1. On the Layout - Application Layers page, the **Global Layer** link should say **Platform Layer** to match the style of the Product Layer link. Or change **Product Layer** link to **Contextual**.

2. The text in the visual is difficult to read.  

Please ignore this comment if this has been addressed somewhere else. :)

**Comment by technabors** [comment]
295 can be closed. That doc is no longer on the site, it relates to the hidden file `_docs/layouts/architecture.md` which was causing confusion. At this point the non-conceptual content is contained within components/navigation category
