### ISSUE TITLE
How to discuss K:V in documentation

### ISSUE THREAD

**Issue by technabors** [rackerlabs/design-system#338]
@nimbinatus pointed out that the way we use the key value terminology is at best not consistent and  at worst confusing across the site. Key, pun intended, offender here is the following article:

http://staging.design.rax.io/design-system/components/key-value-pairs.html

Ideally we have someone take another pass at editing this content.

**Comment by DonNateR** [comment]
I'll have @ReneeRendon read this over and give her recommendations.

**Comment by ReneeRendon** [comment]
Okay, I found a few things that I'd change to make it easier to understand for the reader.

- In the first sentence, I would describe “key” first and “value” second, to align with the name. It is fulfills the reader’s expectation of the definition. Maybe something like, *“Key-value pairs display the label (the key) with the corresponding data (the value).”*

*INTRO*
- I would use the same definition for “key” in the Introduction section as in the first paragraph. In one place it is described as a label. In the other place, it is described as “an identifier for data”. Maybe something like, *“Use key-value pairs when a key (label) needs either text or a visual display of that key’s corresponding value (data).*

*BEST PRACTICES*
- This sentence doesn’t make sense to me. “Ensure key values correspond with the label used for the data.” I thought the key was the label, which would make this statement equal, “Ensure [label and display data] correspond with the label used for the data.” Maybe something like, *“Ensure the value (data) corresponds with the key (label).”*

- An example with an arrow labeled KEY pointing to a specific key and one labeled VALUE pointing to a specific value would be extremely helpful. I was scanning the page to find that when I read the first paragraph and then when I read the intro. I then Googled to find an example before continuing to read the Helix doc to ensure that I understood correctly. (I found the Bugs Bunny example and had the aha! moment.)  If you can't have arrows pointing to an example key and value, maybe explain a simple example like: 
(key) *First Name*   (value) *Bugs*
(key) *Last Name*  (value) *Bunny*

- “Limit key values to one line.”  Does this mean to limit the key and the value? Or just the key label? If it is the first, then it should say key-values.

- “Use the vertical key pattern if key value sections are arranged on the page side by side.” Add text and anchor: (See Vertical key values) 
Also, should it be key-value? That hyphen is extremely important with this topic.

- “Consider breaking key-value pairs into subgroups if there are more than five sets of pairs.” This could definitely use an example.

*DEFAULT LAYOUT*
-“Space between the key and data values must align with the grid gutter between the second and third columns.” I like this sentence! Using the word combination “data values” is very helpful.

*TWO LINES*
- “In certain cases, key-value pair text can wrap to two lines. We recommend formatting key labels across two columns and values across four.” I like this as well! Using the combination of “key labels” is helpful. 

*VERTICAL KEY VALUES*
- “Vertical key value pairs list the key value above the data …” . Should this have the hyphen? It makes better sense to me with the hyphen. I could be wrong on this though.  “Vertical key-value pairs list the key label above the value data …”

**Comment by technabors** [comment]
@ReneeRendon Would you care to create a PR with your suggested edits?
