### ISSUE TITLE
Move Submit Issue button

### ISSUE THREAD

**Issue by technabors** [rackerlabs/design-system#360]
There were a couple different opinions on where to place the submit issue button. It is currently in the upper right of the the docs page template but there were suggestions to move it into the header area that has the preview-image, page.title, and page.usage blurb. 

I can tinker with placing it somewhere but wanted to file and issue in the event someone had a strong opinion and wanted to mock up placement.

@araiford @palindromebart @racksmangonzalez @etytaylor @nimbinatus Thoughts on this one?

**Comment by technabors** [comment]
Anyone else want to weigh in? Sounds like we have differing opinions on location and overall design of this feature.

**Comment by nimbinatus** [comment]
I prefer the current layout or Drew's adjustment. I'm concerned about (1) the layout on small screens (responsive design) and (2) having it look cluttered in the lighter section.

**Comment by racksmangonzalez** [comment]
![helix_submitbuttonthing_01](https://user-images.githubusercontent.com/15747728/33092382-a2a49ede-cebf-11e7-8791-98008e9dfa0a.png)
![helix_submitbuttonthing_02](https://user-images.githubusercontent.com/15747728/33092383-a2b849fc-cebf-11e7-9392-c5ee2aac65e6.png)
![helix_submitbuttonthing_03](https://user-images.githubusercontent.com/15747728/33092387-a2c8c85e-cebf-11e7-9b20-54974abb48f3.png)
![helix_submitbuttonthing_04](https://user-images.githubusercontent.com/15747728/33092388-a2d7f658-cebf-11e7-89de-0cd7ab9e7ac8.png)

**Comment by racksmangonzalez** [comment]
Image 3 is the most functionally correct, accords with best practices, and even with Rackspace design best practices (actions in top right) Image 2 and 4 are tenable, but just bad interior design, like putting a couch in the middle of the room. It locks things in and squishes them.

**Comment by racksmangonzalez** [comment]
![helix_submitbuttonthing_05](https://user-images.githubusercontent.com/15747728/33092547-0e1aab5e-cec0-11e7-9c2e-76b178bb6570.png)
![helix_submitbuttonthing_06](https://user-images.githubusercontent.com/15747728/33092548-0e352e16-cec0-11e7-9eb1-21377cb6ca7c.png)

Additional options I don't recommend.

**Comment by palindromebart** [comment]
What's the problem with current placement? #I'mnothere #onvacay
#cantstopwontstop

**Comment by palindromebart** [comment]
@araiford @technabors @nimbinatus 

What's the problem with keeping it in the "current placement" in the header bar?

**Comment by araiford** [comment]
@palindromebart 

Issues we discussed in [the original bowling session](https://docs.google.com/document/d/13rhLD3z_IeIMV0N6LzWCnN5610iKPf3oAqvQLlegqjw/edit#heading=h.124spzqje8ma) were that the button in the breadcrumb header made it seem more like you were submitting an issue for the site, rather than the component.  

Having the button in the header also felt like a strange mix of navigation (breadcrumbs) and actions (creating an issue).

Also, once we decided to remove the Sketch Template link, it seemed even weirder to have the button hanging out there, outside of the component context.

The idea was that putting the button in the component header enhanced the idea that the user is submitting an issue for the component.

**Comment by palindromebart** [comment]
@araiford @nimbinatus @technabors 
Gotcha. OK I vote for Evan's "Option 1" 

Put the button left aligned beneath the intro text to the component page.
It doesn't have to be below the thumbnail image though, nor should it be fixed to the bottom of the darker bg area. Instead, just float it left one line below the text. Does that make sense?

**Comment by technabors** [comment]
@palindromebart I truthfully don't like my option1 after we discussed last week. It looks fine in that snippet but when you see it on the page it breaks up of the flow of the document. I prefer something closer to @araiford suggestion or @racksmangonzalez option 1 / 3

**Comment by araiford** [comment]
@technabors 

I chatted with Bart & Ty.  For now, let's go with the option I posted.

![image](https://user-images.githubusercontent.com/933210/33286705-d1765a98-d37b-11e7-951f-f67a0256a041.png)

**Comment by araiford** [comment]
oops!  accidentally hit the close button.  reopened...
