### ISSUE TITLE
Update Eyebrow Dropdown Specs

### ISSUE THREAD

**Issue by palindromebart** [rackerlabs/design-system#361]
Updated dropdown specs need to be added to eyebrow specs. 
![17 eyebrow prod nav specs for helixized pilot](https://user-images.githubusercontent.com/5124722/32965014-c20e4f7c-cb9a-11e7-9136-a2844b7cdb2c.png)

**Comment by palindromebart** [comment]
ignore the product nav specs in this image. I'm filing another bug issue to update those.

**Comment by technabors** [comment]
@palindromebart This is being fixed in the following PR #417 

Updated screen-grab of the page. Look at sections Drop-down menu and Drop-down menu item 3/4 of the way down the image

![image](https://user-images.githubusercontent.com/586682/33893266-9e96d534-df20-11e7-9edd-1aaeb577989f.png)
