### ISSUE TITLE
Define, document and update dropdown button specs for the dropdown container

### ISSUE THREAD

**Issue by palindromebart** [rackerlabs/design-system#363]
1) Need to define the appearance specs for dropdown buttons dropdown container

Text styles: 
Category label- ? (could be similar to dropdown) 
Option- tertiary button style only left justified
Disabled options- ? 

Dropdown container:
stroke of outline- ? (could be the same as a dropdown selector)
fill- ? (maybe #ffffff)

2) document it

3) update the website with specs

**Comment by technabors** [comment]
This has to do with the dropdown menu, for example actions-menus and the like may require labels and groups.

Content would extend the following page: helix.rax.io/components/buttons.html#drop-down-buttons

**Comment by nimbinatus** [comment]
Issue complete.
See https://github.com/rackerlabs/design-system/blob/staging/_component_design/buttons.md#drop-down-buttons
