### ISSUE TITLE
Side nav anchors different weights

### ISSUE THREAD

**Issue by technabors** [rackerlabs/design-system#375]
Items contained in the side-nav that exist as stand alone `<a>` tags different in font-weight when compared to `<hx-reveal>` items. The anchor elements need to be adjusted from weight 300 to weight 400 to erase this visual discrepancy.

**Comment by technabors** [comment]
![image](https://user-images.githubusercontent.com/586682/33083719-c2124f6a-cea5-11e7-9d06-fa83e4e79c92.png)

**Comment by nimbinatus** [comment]
closed by #380
