### ISSUE TITLE
Issue Regarding - /components/

### ISSUE THREAD

**Issue by technabors** [rackerlabs/design-system#389]
**I want to...** 

- [ ] Propose an update to an existing design.
- [ ] Report a bug with the current documentation.
- [ ] Work with the team to build a new pattern for to be considered for inclusion in Helix.
- [x] Other, explain below

**Tell us a little more about your request?**

Currently the Breadcrumbs in the eyebrow on the site direct users to a components index page. This page has no style. I suggest we either style it with the family page layout or remove the breadcrumb link to this page.

@araiford Thoughts ^

![image](https://user-images.githubusercontent.com/586682/33392224-0b80c256-d501-11e7-8319-e2b1a8984e4c.png)

**How would you like to collaborate with us on this issue?** 

- [ ] I’d like to communicate via GitHub
- [ ] I’d like to communicate via Slack
- [x] I’d like the Helix team to handle it from here

**Comment by nimbinatus** [comment]
Whoops; I knew I forgot something ;)

**Comment by araiford** [comment]
yep, we should make the "components" part of that non-clickable, and modify it somehow so it looks different.

**Comment by technabors** [comment]
@araiford So we can fix this without overriding anything from helix-ui with a simple inline edit. I don't like inlining but this might be the easiest solution in this case.

I.e. existing breadcrumb code is as follows. 

`<a href="{{site.url}}/components/index.html" style="">{{page.category}}</a>`

Solution to fix is two part, remove the `href` value and  remove the `cursor:pointer` value. 

`<a style="cursor:default;">{{page.category}}</a>`
