### ISSUE TITLE
Issue Regarding - /components/badge

### ISSUE THREAD

**Issue by racksmangonzalez** [rackerlabs/design-system#392]
**I want to...** 

- [x] Propose an update to an existing design.
- [x] Report a bug with the current documentation.
- [ ] Work with the team to build a new pattern for to be considered for inclusion in Helix.
- [ ] Other, explain below

**Tell us a little more about your request?**
The documentation indicates the color for the badges on the bell be red 900 but the actual color in the mock is incorrect. It's close to red 500 #F44336 but the actual color in the documentation is actually #F12923. It should be #d32f2f as indicated in the documentation. I've made the changes in the Sketch doc for badges. 

**How would you like to collaborate with us on this issue?** 

- [ ] I’d like to communicate via GitHub
- [ ] I’d like to communicate via Slack
- [x] I’d like the Helix team to handle it from here

**Comment by technabors** [comment]
Closing, this issue was resolve in the following PR https://github.com/rackerlabs/design-system/pull/428
