### ISSUE TITLE
Issue Regarding - Incorrect spacing on some headers

### ISSUE THREAD

**Issue by ChristieQ** [rackerlabs/design-system#394]
**I want to...** 

- [ ] Propose an update to an existing design.
- [x] Report a bug with the current documentation.
- [ ] Work with the team to build a new pattern for to be considered for inclusion in Helix.
- [ ] Other, explain below

**Tell us a little more about your request?**
Looks like the spacing on some of the headers is incorrect. This screen shot is from the Color Palette page.
<img width="954" alt="screen shot 2017-12-01 at 1 41 33 pm" src="https://user-images.githubusercontent.com/8559341/33500189-a025cfa8-d69d-11e7-9afd-488cf932f8ea.png">

**How would you like to collaborate with us on this issue?** 

- [ ] I’d like to communicate via GitHub
- [ ] I’d like to communicate via Slack
- [x] I’d like the Helix team to handle it from here

**Comment by nimbinatus** [comment]
Thanks for the notification! This one has been fixed by https://github.com/rackerlabs/design-system/issues/334 and the related push to production (https://github.com/rackerlabs/design-system/pull/399). Component page spacing landing after #379 hits master. Checked against FF57 and Chrome62
