### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by izrik** [rackerlabs/design-system#404]
**I want to...** 

- [ ] Propose an update to an existing design.
- [x] Report a bug with the current documentation.
- [ ] Work with the team to build a new pattern for to be considered for inclusion in Helix.
- [ ] Other, explain below

**Tell us a little more about your request?**
The repo does not contain a `LICENSE` file indicating what end users can do with the files in the repo. Are these files available for use only for Rackspace products? or are other people allowed to use them? This should be clarified. IANAL, but my understanding is that a repo without a specified license defaults to "All Rights Reserved", which would mean that any interested third parties would not be able to use  the contents of the repo.

**How would you like to collaborate with us on this issue?** 

- [x] I’d like to communicate via GitHub
- [x] I’d like to communicate via Slack
- [x] I’d like the Helix team to handle it from here

**Comment by technabors** [comment]
Howdy @izrik, thanks for your submission. @CITguy and myself looked into the issue. Good news, it appears you are correct that no license defaults to "All Right Reserved". Source:  https://help.github.com/articles/licensing-a-repository/

![image](https://user-images.githubusercontent.com/586682/33679397-45df9106-da84-11e7-95d2-7269eb1e221a.png)

However, I have taken an action to discuss this further with the team. We will be discussing during our next team sync. Currently there is no proprietary information on the repo and we plan to keep it that way. However if that changes we will move this into an internal repo.

**Comment by technabors** [comment]
This item was discussed in our bowling meeting on 12/07/17.

"Decision: We are ok with no license for the time being. Down the road we might want to add a non open source license for now the ToS works as there is no proprietary info."

Closing this issue per the discussion.
