### ISSUE TITLE
Button focus state documentation

### ISSUE THREAD

**Issue by eddywashere** [rackerlabs/design-system#409]
**I want to...** 

- [ ] Propose an update to an existing design.
- [x] Report a bug with the current documentation.
- [ ] Work with the team to build a new pattern for to be considered for inclusion in Helix.
- [ ] Other, explain below

**Tell us a little more about your request?**

Focus state documentation for buttons (and verify that other focus states are not missing). Also, I did not see this in the helix ui toolkit.

**How would you like to collaborate with us on this issue?** 

- [ ] I’d like to communicate via GitHub
- [ ] I’d like to communicate via Slack
- [x] I’d like the Helix team to handle it from here

This is what we're using in the mean time:

![image](https://user-images.githubusercontent.com/399776/33730510-083a1414-db35-11e7-917b-b2c216bb24f4.png)

**Comment by eddywashere** [comment]
updated screenshot to match input focus color

**Comment by nimbinatus** [comment]
Fixed by #532

**Comment by nimbinatus** [comment]
@eddywashere the next release of the Helix design site should have these docs. I'll post the PR for the next release when it comes up, and I'll send you the staging site link privately in the meantime.

cc: @araiford
