### ISSUE TITLE
Issue Regarding - 404 Error linking from home page

### ISSUE THREAD

**Issue by ChristieQ** [rackerlabs/design-system#412]
**I want to...** 

- [ ] Propose an update to an existing design.
- [ ] Report a bug with the current documentation.
- [ ] Work with the team to build a new pattern for to be considered for inclusion in Helix.
- [ ] Other, explain below

**Tell us a little more about your request?**
- "Pattern Guidelines" links back to the home page
- "Sketch Resources" leads to a 404 error

![screen shot 2017-12-07 at 3 57 11 pm](https://user-images.githubusercontent.com/8559341/33740771-65bf3c90-db67-11e7-8b93-6f525a8442ed.png)

- Invision icon links back to home page
<img width="277" alt="screen shot 2017-12-07 at 4 05 23 pm" src="https://user-images.githubusercontent.com/8559341/33741049-809c1032-db68-11e7-82be-1e2313390d1a.png">

**How would you like to collaborate with us on this issue?** 

- [ ] I’d like to communicate via GitHub
- [ ] I’d like to communicate via Slack
- [x] I’d like the Helix team to handle it from here

**Comment by nimbinatus** [comment]
Thanks, @ChristieQ ! I'll take care of this one today.
