### ISSUE TITLE
[BUG] Known SVG Issues

### ISSUE THREAD

**Issue by nimbinatus** [rackerlabs/design-system#420]
There are a number of issues with adding SVGs to the site, and this issue attempts to compile them for reference (and for potential future fixes). Here's an incomplete list:

- [ ] Fonts don't appear properly if they're not explicitly embedded.
- [ ] Some text gets offset by a lot at export time.

**Comment by technabors** [comment]
I suggest we turn this into a 8-13 point story that goes through the site and swaps all SVGs for 2x pngs. Many of the newer pages, those done half-way through the redesign used 2x pngs and the format doesn't have the issues the SVGs do.
