### ISSUE TITLE
Page layouts: Redline image and content don't match

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/design-system#430]
**I want to...** 

- [ ] Propose an update to an existing design.
- [x] Report a bug with the current documentation.
- [ ] Work with the team to build a new pattern for to be considered for inclusion in Helix.
- [ ] Other, explain below

**Tell us a little more about your request?**

Looking at the Redlines on the images versus the written content in the “Base layouts” section. The Redlines point to “Utility Nav” whereas the first bullet describes a “account navigation bar” that is used to “navigate between applications, manage roles, and manage preferences on both the user and the account level.” 

Besides making sure the redline matches the content, is the top nav portion of the page still defined as "utility nav"? If so, is the utility nav only used for account navigation or can it be used for more? We should address this question in the content, and maybe define a standard term for the top navigation bar.

**How would you like to collaborate with us on this issue?** 

- [x] I’d like to communicate via GitHub
- [x] I’d like to communicate via Slack
- [ ] I’d like the Helix team to handle it from here

**Comment by technabors** [comment]
@DonNateR See #431 content was adjusted in the first paragraph to align content with the redline images.

Re: "Besides making sure the redline matches the content, is the top nav portion of the page still defined as 'utility nav'?" -Yes, we will be using utility nav more consistently in the future as per this issue, the above PR, and the conversation we had with @ReneeRendon today.

Re: "If so, is the utility nav only used for account navigation or can it be used for more?" - AS written it is used to, "navigate between applications, manage roles, and manage preferences on both the user and the account level.” If this is not sufficient please provide suggestions on how to bolster the content.
