### ISSUE TITLE
Inconsistency with Buttons Specs

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/design-system#438]
Migrated from rackerlabs/helix-ui#130
CC: @cyrichardson 

**I want to...** 
- [ ] Propose an update to an existing design.
- [x] Report a bug with the current documentation.
- [ ] Work with the team to build a new pattern for to be considered for inclusion in Helix.
- [ ] Other, explain below

**Tell us a little more about your request?**
http://helix.rax.io/components/buttons.html - 1st bullet says Button Text style should always be Title Case where the first letter of each word is capitalized.

Button figure after the first couple do show Title case, it's just the 1st set that do not.

**How would you like to collaborate with us on this issue?** 

- [ ] I’d like to communicate via GitHub
- [ ] I’d like to communicate via Slack
- [x] I’d like the Helix team to handle it from here

**Comment by cyrichardson** [comment]
@CITguy.  So sorry I opened this in wrong repo. Thanks so much for moving it to the correct place.

**Comment by DonNateR** [comment]
- [ ] JIRA: Copy edit images to ensure that they follow button text style. Replace all SVGs with PNGs.

**Comment by nimbinatus** [comment]
Fixed in #565
