### ISSUE TITLE
Search Input scaling issue.

### ISSUE THREAD

**Issue by technabors** [rackerlabs/design-system#454]
**I want to...** 

- [ ] Propose an update to an existing design.
- [ ] Report a bug with the current documentation.
- [ ] Work with the team to build a new pattern for to be considered for inclusion in Helix.
- [x] Other, explain below

**Tell us a little more about your request?**

Search bar goes out of form when scroll bar is introduced to side-navigation (see screenshot)

![image](https://user-images.githubusercontent.com/586682/36813080-eef27398-1c98-11e8-85ff-700a4f46128c.png)

In the above image the scroll bar was introduced to the side-nav by expanding the components reveal section causing the scroll bar to take up ~10px of the sidenav container and causing the search place holder content to wrap and extend the containing input.

**How would you like to collaborate with us on this issue?** 

- [ ] I’d like to communicate via GitHub
- [ ] I’d like to communicate via Slack
- [x] I’d like the Helix team to handle it from here

**Comment by nimbinatus** [comment]
Fixed in #466
