### ISSUE TITLE
Content to clarify

### ISSUE THREAD

**Issue by chri2547** [rackerlabs/design-system#459]
**I want to...** 

- [ ] Propose an update to an existing design.
- [X] Report a bug with the current documentation.
- [ ] Work with the team to build a new pattern for to be considered for inclusion in Helix.
- [ ] Other, explain below

**Tell us a little more about your request?**

In tabset.md, I don't understand the following When to use item: "You want to eliminate the need to stack sections."

In popover.md, I don't understand the following When to use item: "Popovers are triggered as a result of a user action and provide a user with additional context through language, actions through buttons, or both." 

**How would you like to collaborate with us on this issue?** 

- [x] I’d like to communicate via GitHub
- [x] I’d like to communicate via Slack
- [ ] I’d like the Helix team to handle it from here

**Comment by technabors** [comment]
## Popovers

`"Popovers are triggered as a result of a user action and provide a user with additional context..."`

Popovers appear when a user interacts with an action link on a page. For instance a user clicks an `Edit` link next to something within an interface. This edit task can have multiple parameters to edit so a popover is displays which displays those parameters. 

`"..through language, actions through buttons, or both."`

A popover is just a container object that appears above the current page and may contain various content based on the function the popover is serving. To continue our example from above our edit popover may have a Header titled, "Edit Foo Object", a couple dropdowns to edit Parameter1 and Parameter2, and two buttons to Confirm or Cancel.

## Tabs

`"You want to eliminate the need to stack sections."`

Using tabs allows you to use screen space more concisely. For example we have three tabs tab1 / tab2 / tab3 and each has content that is displayed when that tab is selected. If you needed to display all this information on a page but didn't use tabs you would need to have section 1 followed by section 2 and then section3. This would make the page longer.

**Comment by chri2547** [comment]
All set. Thanks for clarifying!
