### ISSUE TITLE
Issue Regarding - Home

### ISSUE THREAD

**Issue by technabors** [rackerlabs/design-system#461]
**I want to...** 

- [ ] Propose an update to an existing design.
- [x] Report a bug with the current documentation.
- [ ] Work with the team to build a new pattern for to be considered for inclusion in Helix.
- [ ] Other, explain below

**Tell us a little more about your request?**

Homepage link for `Installation Guide` is directing users to a removed page on helix-ui side. Need to update the link to point to `https://rackerlabs.github.io/helix-ui/guides/getting-started/`

**How would you like to collaborate with us on this issue?** 

- [ ] I’d like to communicate via GitHub
- [ ] I’d like to communicate via Slack
- [x] I’d like the Helix team to handle it from here

**Comment by nimbinatus** [comment]
Fixed by https://github.com/rackerlabs/design-system/pull/463

**Comment by nimbinatus** [comment]
Fixed in staging; will be fixed in production on the next prod release. Closing issue.
