### ISSUE TITLE
Head styles for non-Pilot projects

### ISSUE THREAD

**Issue by mocha** [rackerlabs/design-system#469]
**I want to...** 
- [ ] Work with the team to build a new pattern for to be considered for inclusion in Helix.

**Tell us a little more about your request?**
I'm building an internal tool for Racker-only use. I need guidelines around what the **logo** should look like and how it should function when it's an internal tool. Can I swap it out with the name of my tool? Does the name go to the right of the Rackspace logo?

**How would you like to collaborate with us on this issue?** 

- [ ] I’d like to communicate via GitHub

**Comment by nimbinatus** [comment]
Thanks for the request, @mocha! I'll make sure this question gets posed to our designers so we can help provide guidance.

**Comment by DonNateR** [comment]
- [ ] Add JIRA card for eyebrow modification for non-pilot headers.
