### ISSUE TITLE
Issue Regarding - /components/breadcrumbs

### ISSUE THREAD

**Issue by mocha** [rackerlabs/design-system#470]
**I want to...** 

- [ ] Propose an update to an existing design.

**Tell us a little more about your request?**
Regarding this: _"If the page title is longer than necessary, use shortened variations of the title. For example, instead of Billing overview, use Overview."_

If the content is user-generated, you can't "use shortened variations". There needs to be a machine-implementable fallback as well. I'd suggest "For strings of length>12 characters, show only the first and last 4 characters, joined by an ellipsis."

Examples below:
8. ABCDEFGH
9. ABCDEFGHI
10. ABCDEFGHIJ
11. ABCDEFGHIJK
12. ABCD...IJKL
13. ABCD...JKLM
14. ABCD...KLMN

**How would you like to collaborate with us on this issue?** 

- [ ] I’d like to communicate via GitHub

**Comment by DonNateR** [comment]
- [ ] Make JIRA to add "Too long page title" section to breadcrumbs doc.
