### ISSUE TITLE
Submit Issue from any page

### ISSUE THREAD

**Issue by mocha** [rackerlabs/design-system#471]
**I want to...** 

- [ ] Propose an update to an existing design.

**Tell us a little more about your request?**
I should be able to submit an issue from any page on the site. Not everything is a component, and currently only the components have a "submit issue" button. For example - Typography problems.

**How would you like to collaborate with us on this issue?** 
- [ ] I’d like the Helix team to handle it from here

**Comment by DonNateR** [comment]
- [ ] Move issue to JIRA. Create a design exploration story.
