### ISSUE TITLE
search results page images wonky

### ISSUE THREAD

**Issue by palindromebart** [rackerlabs/design-system#477]
images are off-center and squared off weirdly. 
![screen shot 2018-03-14 at 2 03 09 pm](https://user-images.githubusercontent.com/5124722/37425367-1c338dda-2791-11e8-96b3-6b81ab91c680.png)

**I want to...** 

- [ ] Propose an update to an existing design.
- [x] Report a bug with the current documentation.
- [ ] Work with the team to build a new pattern for to be considered for inclusion in Helix.
- [ ] Other, explain below

**Tell us a little more about your request?**

**How would you like to collaborate with us on this issue?** 

- [ ] I’d like to communicate via GitHub
- [ ] I’d like to communicate via Slack
- [x] I’d like the Helix team to handle it from here

**Comment by nimbinatus** [comment]
Debug note: A hard refresh (SHIFT+Refresh button) fixed it, and we can't seem to duplicate it again. Please add more screenshots if you have the same problem.

**Comment by DonNateR** [comment]
Tried recreating this on my end and couldn't duplicate. Can we get one more person to try and validate than close this out if they can't recreate the problem?

**Comment by DonNateR** [comment]
Will create a JIRA ticket to update the Helix ops playbook to add time stamps for a hard refresh for every new release.

**Comment by nimbinatus** [comment]
Can't duplicate; probably was a caching issue. Closing issue.
