### ISSUE TITLE
Search results page title is crammed against the top of the page

### ISSUE THREAD

**Issue by palindromebart** [rackerlabs/design-system#478]
page title could use some breathing room.
![screen shot 2018-03-14 at 2 09 20 pm](https://user-images.githubusercontent.com/5124722/37425459-6587e710-2791-11e8-8225-f30295dcb107.png)

**I want to...** 

- [ ] Propose an update to an existing design.
- [x ] Report a bug with the current documentation.
- [ ] Work with the team to build a new pattern for to be considered for inclusion in Helix.
- [ ] Other, explain below

**Tell us a little more about your request?**

**How would you like to collaborate with us on this issue?** 

- [ ] I’d like to communicate via GitHub
- [ ] I’d like to communicate via Slack
- [ x] I’d like the Helix team to handle it from here

**Comment by nimbinatus** [comment]
Debug note: A hard refresh (SHIFT+Refresh button) fixed it, and we can't seem to duplicate it again. Please add more screenshots if you have the same problem.

**Comment by araiford** [comment]
Closing due to it being a caching issue.  Will take the caching issue separately.
