### ISSUE TITLE
Strange font on Windows machine

### ISSUE THREAD

**Issue by chri2547** [rackerlabs/design-system#488]
**I want to...** 

- [ ] Propose an update to an existing design.
- [X] Report a bug with the current documentation.
- [ ] Work with the team to build a new pattern for to be considered for inclusion in Helix.
- [ ] Other, explain below

**Tell us a little more about your request?**
I see L SEP periodically on the Helix site page. I've attached a screen shot as a visual aid. I have a Windows machine.
![font-weirdness](https://user-images.githubusercontent.com/35463610/37847887-5dcf94b2-2ea0-11e8-8310-2aa4ec00ffdb.png)

**How would you like to collaborate with us on this issue?** 

- [ ] I’d like to communicate via GitHub
- [ ] I’d like to communicate via Slack
- [ ] I’d like the Helix team to handle it from here

**Comment by nimbinatus** [comment]
Ref for next bug hunt, maybe an encoding issue?: https://github.com/rackerlabs/design-system/blame/staging/_component_design/selector-strip.md#L87

Verified present on ChromeOS

Thanks, @chri2547 !
