### ISSUE TITLE
Typo: Container Spacing Variants

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/design-system#540]
**I want to...** 

- [ ] Propose an update to an existing design.
- [x] Report a bug with the current documentation.
- [ ] Work with the team to build a new pattern for to be considered for inclusion in Helix.
- [ ] Other, explain below

**Tell us a little more about your request?**
The "XS" bullet to the left of the image in STYLE > Spacing # Container Spacing Variants has an incorrect value. It should be `8px` to match the specification in the graphic.

<img width="1146" alt="screen shot 2018-06-14 at 3 09 14 pm" src="https://user-images.githubusercontent.com/545605/41435611-0e76618a-6fe5-11e8-96e1-090380172ca5.png">

**How would you like to collaborate with us on this issue?** 

- [ ] I’d like to communicate via GitHub
- [ ] I’d like to communicate via Slack
- [x] I’d like the Helix team to handle it from here

**Comment by nimbinatus** [comment]
Fixed in #551 & #553
